### ISSUE TITLE
module in example code is not installed

### ISSUE THREAD

**Issue by maxadam2017** [fasrc/User_Codes#12]
https://github.com/fasrc/User_Codes/tree/master/Parallel_Computing/MPI
the example suggests loading the modules: intel/23.0.0-fasrc01 and openmpi/4.1.4-fasrc01 but these modules are not available and throws the error, 
Lmod has detected the following error:  The following module(s) are unknown: "intel/23.0.0-fasrc01" "openmpi/4.1.4-fasrc01"

**Comment by maxadam2017** [comment]
I am helping a user (rt 165228) and had pointed them to our docs, they tried to run the example code and responded with the error.

**Comment by pedmon** [comment]
Yeah, we are in a weird state where some of our docs are updated to Rocky 8 while others are CentOS 7.  I would instruct them to use their favorite modules on the CentOS 7 side of the house, finding them using the usual module commands.

**Comment by pedmon** [comment]
I've updated the doc to indicate that those listed are only possible combinations, not a complete list. I don't want to provide a full listing of modules here as we update them regularly. The source of truth is the module system itself so I added a note to use module spider.
