### ISSUE TITLE
Install instructions here differ from docs.rc.fas.harvard.edu

### ISSUE THREAD

**Issue by maxadam2017** [fasrc/User_Codes#17]
The instructions at https://docs.rc.fas.harvard.edu/kb/spack/ instruct to use this command to install spack: <br>`git clone -c feature.manyFiles=true https://github.com/spack/spack.git` <br>which will install the default "develop" branch, but this readme.md instructs to use:  <br>`git clone --depth=100 --branch=releases/v0.20 https://github.com/spack/spack.git`<br>which will lock the user onto the v0.20.0 branch.  These instructions should tell users to use the default develop branch so that updating is a simple git pull.

**Comment by pedmon** [comment]
I've rectified our docs to mirror what the Spack official docs say. If users what to pull a branch they may do so at their own peril.
